### ISSUE TITLE
searchFields not working

### ISSUE THREAD

**Issue by f108156106** [lekoala/bootstrap5-tags#103]
I use **searchFields** attribute filter option,
but searchFields render data-attribute on **li** tag, not **a** tag,

and

I use QIP_NO , but become data--q-i-p_-n-o attribute

**Comment by lekoala** [comment]
if you have an example jsfiddle or codepen that would be very helpful to determine your issue

**Comment by f108156106** [comment]
https://jsfiddle.net/3soavt0z/

I will not found item if searchFields not contain label and value

**Comment by lekoala** [comment]
@f108156106 thanks this is very helpful. i think it's due to the uppercase that's messing up with the data attributes. i've changed how it's stored to use a set key and store everything as json instead. it's less pretty but it seems to work
https://github.com/lekoala/bootstrap5-tags/commit/b9ba8dfe4ab1902f0b88756d861a21ccea9025bf

**Comment by f108156106** [comment]
It's working! Thanks~
In addition, I found some function at Tags.prototype, but it seems not include document, I hope update document content.
For example, I want to clear tags value, but I couldn't found function to clear, so I use "hide function" like "reset()" to clear.
Another case, I want to change option of instanced tags, I use "setData()" and "reset()" function to update tags.
Another case, I want to set value on instanced tags, I use "setItem()" and "resetSearchInput()" function to set value.
If it adds "change options", "set values" function, and updates the document, it will to be well.

**Comment by lekoala** [comment]
i add an updateData and a clear method
https://github.com/lekoala/bootstrap5-tags/releases/tag/1.6.12

i don't tend to use it myself programmatically so indeed the api is a bit lacking 
if you find other things that may be of use you can open a pr

**Comment by f108156106** [comment]
@lekoala Can you update readme.md? Thanks~

**Comment by lekoala** [comment]
@f108156106 none of the public methods are documented so far. I would probably just add a bunch of jsdoc on top of the method to explain what it does and then use jsdocs to generate some readable files
but then i would need to document everything so that it's consistent so that's for another day :-)
