### ISSUE TITLE
Keeping form inputs after sending

### ISSUE THREAD

**Issue by staminem** [lekoala/bootstrap5-tags#3]
Hi and thanks again for this awesome plugin.
I'm trying to keep the inputs a user makes in the tags input field after sending the form. For simple text input fields, adding
`value="{{ request.form['id of the field'] }}"`
keeps the values after input. Is there a way to achieve something similar fot the tags inputs? Would have to be applicable to newly added tags.
Thanks a lot!

**Comment by lekoala** [comment]
@staminem since this is a select[multiple] replacement, you would have to do some work on actually making a loop over the array and create the relevant options but that should be feasible. i don't think there is anything i can do here since it's more related to how you generate your inputs

**Comment by lekoala** [comment]
optionally, as a convenience, it wouldn't be too hard to store the value somewhere in a data attribute and create the relevant tags on init

**Comment by staminem** [comment]
yes i understand, thank you! i will probably try something using localstorage or similar

**Comment by mariusa** [comment]
Related question: when using server to fetch values, we get both value & label columns. The selected tags are available only as values.
Use case: when user comes back to the form to edit, need to restore the existing values, but also labels.
https://vue-multiselect.js.org/ does this by returning an array with objects `[{value: 123, label: 'abc'},...]` , not just `['123']`.  This helps a lot as we don't have to lookup items again on server to fetch the labels.
I realize `<select multiple` works only with an array of values.

Would it be possible to have 2 methods, `get/set options`, which return and accept an array of objects?

**Comment by lekoala** [comment]
I think nothing prevents you from adding the option before initializing the tags input ? or am i missing something? if you want to create a get/set options as a PR you are welcome to do so :)

**Comment by lekoala** [comment]
well, since you provided the list in the first place, you know what value matches which label.
if you have a db with id => title, your server call return the list. when submitted, you only get the id, but since you have the db at hand, there is no need to have the name.
when reloading the page, simply populate the select with the proper options. you can also see how i add options in the demo.
sorry maybe i'm missing something but i don't see the issue :)

**Comment by mariusa** [comment]
> but since you have the db at hand, there is no need to have the name.

Name also needs to be saved, in order to avoid implementing another API which accepts a list of ids and returns a list of names. 

In the demo, I don't see how to dynamically add options. I only see options pre-populated with HTML:
```
<option value="1" selected="selected">Apple</option>
```

How to make the server demo example pre-loaded with both 'fr' and 'en' (and labels) ? With JS, not HTML, and without making a server call.

Appreciate your time on this :)

**Comment by lekoala** [comment]
This is how I add an option

https://github.com/lekoala/bootstrap5-tags/blob/dd57aa00ed7a73d09e3d320219fb9fb8104912ba/demo.html#L76-L90

I don't know how you load the initial data, but it has to be another api endpoint anyway no? The endpoint providing suggestions does just that, nothing else. To load initial data, you do something else, and you can add options in js as required.

**Comment by lekoala** [comment]
i see. that's obviously something i never do because, while it's easier, it has its issues (what if a tag is edited in the meantime? what about multilingual).. but that's another topic.
the thing is : what do you expect when sending the form ? i guess in your case, you don't send the form (in a regular html form submit, it should be an array). 
So you probably need to retrieve the values yourself (that's a loop avec option[selected]) and you can get the pairs of values that you need and save it the way you want. it's basically this with a map instead of a plain value
https://github.com/lekoala/bootstrap5-tags/blob/dd57aa00ed7a73d09e3d320219fb9fb8104912ba/tags.js#L574-L578

Then, in order to restore it, simply loop on the values and add options as needed.
Obviously, that's not as easy as binding a vue model, but it's probably very easy to create a vue something that does the process i described under the hood in a couple of lines

**Comment by mariusa** [comment]
Merci, Thomas! I'll look into this.

Wishing you a good weekend :)
