### ISSUE TITLE
Default bootstrap validation error is not shown for required select

### ISSUE THREAD

**Issue by anray** [lekoala/bootstrap5-tags#32]
When press form's Submit button OOTB bootstrap validation error mesage is not shown for select when it is required.

#bootstrap5

**Comment by lekoala** [comment]
i added the tests in the demo on master, it seems fine with latest release. can you confirm?

**Comment by anray** [comment]
No, the issue is still there.
And your demo has only: "A regular select below to test required"

**Comment by lekoala** [comment]
The first one is required and it seems to work. Otherwise I'm thinking it may depend on the browser I wonder if hidden fields are validated or not. There is a bit of commented code to check all fields specifically instead of the whole form that might help. Otherwise not sure what is the issue so ideas are welcome :)

**Comment by lekoala** [comment]
see screenshot, clear the value of the first element in the demo and try submitting the form

![image](https://user-images.githubusercontent.com/250762/149754293-4f90bcc7-006b-42ee-8817-5e28143efec6.png)

**Comment by lekoala** [comment]
Closing this, feel free to reopen if you find another issue :)
