### ISSUE TITLE
improve suggestions drop-down position 

### ISSUE THREAD

**Issue by mariusa** [lekoala/bootstrap5-tags#47]
The current suggestions drop-down position is right under letters entered by user.
There are some issues with this:
1. using `keepOpen`, the drop-down list position changes/jumps on screen after each selection. 
2. when entering text towards the end of input, the dropdown goes out of screen:
![2022-03-17_15-30](https://user-images.githubusercontent.com/1283842/158819727-9b510b9e-748a-4c5b-bb06-2ebfef7fd38e.png)

Suggested fix: keep drop-down in a fixed position, always under the input, similar to https://vue-multiselect.js.org/ 
This would solve both issues.
![2022-03-17_15-36](https://user-images.githubusercontent.com/1283842/158820190-e5ea7011-3812-4c54-80fa-9d9d6e80e890.png)

**Comment by lekoala** [comment]
actually i'm not a big fan of that super large drop element. i had some computation in place to prevent that from happening, but they seem wrong.
and i didn't handle the case if the element was at the bottom of the page (obviously things can become complicated very complicated within overflow containers, modals, etc). This is also way I let the browser set the position itself without having a relative positioning.

computation should be fixed in https://github.com/lekoala/bootstrap5-tags/releases/tag/1.4.28

**Comment by mariusa** [comment]
Thanks. It still goes out of viewport when entering 3rd item (with dev tools opened, to make it smaller)
![2022-03-18_08-30](https://user-images.githubusercontent.com/1283842/158949342-ddcf5296-4ae7-4bf1-b8d6-004d3a2276aa.png)

**Comment by lekoala** [comment]
Can you make a jsfiddle or codepen so that I can test ?

**Comment by mariusa** [comment]
Looking into it. I couldn't manage so far to reproduce in demo with more values.

**Comment by mariusa** [comment]
It might be because of Vue framework used in my app, elements are added dynamically to DOM.

**Comment by lekoala** [comment]
that's really odd. i cleaned up the maths a little bit. maybe it's the document.body.offsetWidth that is not returning the right value. i did try with the developer's tool open but it works for me.
i've release a new version where you can set the dropdown using the full input width. it doesn't look as good but maybe that works for you.
otherwise, if you want to debug this, i think it's really a matter of setting a couple of console log with the values for the math and see what's going on

**Comment by mariusa** [comment]
Thanks, I'll continue debugging this. Closing for now until I have more info.
