### ISSUE TITLE
Force new tags to use regex

### ISSUE THREAD

**Issue by jackyraimond** [lekoala/bootstrap5-tags#75]
When you're using a regex, it's not only forcing a new tag to use the regex but it's also been used as validation on the existing options.

For example, I'd like to show an existing name and email address, separate by a space. But when I use something like `data-regex="^[^\s@]+@[^\s@]+\.[^\s@]+$"` I can't select the option because of the validation.

Is it possible to only use the regex for new tags and not for the existing ones?

**Comment by lekoala** [comment]
probably it would be cleaner to format the results so that the value is still valid
but i don't see the issue in ignoring the regex for existing options, since they are supposed to be set by you anyway ;-)

for those who need more sophisticated validation, i added a custom callback

https://github.com/lekoala/bootstrap5-tags/releases/tag/1.5.10
