### ISSUE TITLE
Add new tag

### ISSUE THREAD

**Issue by jackyraimond** [lekoala/bootstrap5-tags#77]
You can add a new tag by using the enter key. Is it possible to add a new tag if you use your tab key or click outside the form field?

**Comment by lekoala** [comment]
yes, you can use

addOnBlur | Boolean | Add new tags on blur (only if allowNew is enabled)
separator | Array \| String | A list (pipe separated) of characters that should act as separator (default is using enter key)

**Comment by lekoala** [comment]
or maybe we should leave the value with the invalid message, i don't know :-) i think both logic make sense

**Comment by lekoala** [comment]
@jackyraimond actually, i didn't manage to replicate the issue. the only time the input is cleared is when you try to input the same value twice without allowSame being set. otherwise, the input stays the same.
i did some more tests in the demo https://github.com/lekoala/bootstrap5-tags/commit/21cb596185e6eb971a0f44aa33e3430270d1b9ad
do you have an example with the actual issue?

**Comment by jackyraimond** [comment]
I’m using these settings:

```html

multiple
data-allow-new="true"
data-add-on-blur="true"
data-separator="| , |"
data-allow-clear="1"
data-full-width="1"
data-badge-style="secondary"
data-regex="^[^\s@]+@[^\s@]+\.[^\s@]+$"
data-max="1"

```


If you then fill in an invalid email (for example with a space in the email) and click on enter, you’ll see the invalid feedback message. But if you use tab or click outside the form, it clears the field and not showing the invalid feedback message. This is the case when you try to create a new tag.

**Comment by lekoala** [comment]
@jackyraimond thanks for your input, based on that i can see your issue. so many use cases :-)
https://github.com/lekoala/bootstrap5-tags/releases/tag/1.5.13 this should fix your issue
