### ISSUE TITLE
css class are overwritten on initialization

### ISSUE THREAD

**Issue by lataupe78** [lekoala/bootstrap5-tags#97]
Hi M. Koala,
congratulations for your library !

I have noticed a small issue here : 
Even if I add some css classes to the select ( ie :  "bg-info" or "is-invalid" for validation feedback from server side ) 
these classes are removed by your library

So I added the "is-invalid" class to the  ["form-select-lg", "form-select-sm"] 
in _configureHolderElement() and this class is persisted now, but I would prefer not edit your code 

Am I missing something ?

**Comment by lekoala** [comment]
I'm not by default adding all classes since it's not easy to know how that will impact the fake select element, but validation classes make a lot of sense to track, i added them here
https://github.com/lekoala/bootstrap5-tags/commit/05fd402f479b1337341f70cff48b616c0dc03e9d

i don't know maybe i should just copy everything over to the fake element or add a config property to add some other classes to the holder. never had to do that before :-)

**Comment by lataupe78** [comment]
Thank you for your reactivity ! a config property should do the job well :)
